sudo: false
language: ruby
rvm:
- 2.3.0
- 2.3
- 2.4.0
- 2.4
- 2.5.0
- 2.5
- 2.6.0
- 2.6
gemfile:
- gemfiles/activesupport_4.gemfile
- gemfiles/activesupport_5.gemfile
env:
  global:
  - TZ=Europe/London
  - DB_PASSWORD=""
before_install:
- export TZ=Europe/London
script:
- bundle exec rspec -fd -b -P ./spec/**/*_spec.rb
- ./quality.sh
services:
- postgresql
addons:
  # We have seen some json errors on some DBs, so choose the oldest with jsonb.
  postgresql: "9.4"
cache: bundler
notifications:
  email: false
